# Generated by Django 2.2.2 on 2019-08-23 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cloneapp', '0016_auto_20190823_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='viewed_user',
        ),
        migrations.AddField(
            model_name='videos',
            name='user_viewed',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Viewed_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cloneapp.Videos')),
            ],
        ),
    ]
