# Generated by Django 2.2.2 on 2019-08-27 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloneapp', '0018_preferences'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preferences',
            old_name='teacher',
            new_name='pref',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='topic',
        ),
    ]
