# Generated by Django 2.2.2 on 2019-09-02 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloneapp', '0020_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='videos/', verbose_name='')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloneapp.Videos')),
            ],
        ),
    ]
