# Generated by Django 2.2.2 on 2019-09-04 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloneapp', '0023_auto_20190903_1447'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Thumbnail',
        ),
    ]
