# Generated by Django 2.2.2 on 2019-11-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloneapp', '0027_auto_20191022_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='size',
            field=models.FloatField(default=0),
        ),
    ]
