# Generated by Django 2.2.2 on 2019-11-10 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloneapp', '0028_videos_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
